# Generated by Django 4.1.1 on 2022-10-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now=True)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=10)),
                ('descripcion', models.TextField(max_length=250)),
                ('tamanio', models.IntegerField(choices=[(1, 'Chico (0-10 cm)'), (2, 'Mediano (10-40 cm'), (3, 'Grande (40+ cm')])),
            ],
        ),
    ]
