# Generated by Django 4.1.3 on 2022-11-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cita', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('comentario', models.TextField(max_length=250)),
                ('manera', models.TextField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Cita',
        ),
    ]
