# Generated by Django 4.1.3 on 2022-11-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cita', '0002_contacto_delete_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='numero',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
