# Generated by Django 4.1.3 on 2022-11-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cita', '0004_alter_contacto_manera'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='asunto',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
