# Generated by Django 4.1.3 on 2022-11-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cita', '0006_alter_contacto_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=20, unique=True)),
                ('contrasenia', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
